server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.jks
    key-password: secret
    key-store-password: secret
    protocol: TLS
    enabled-protocols: TLSv1.2
    trust-store: classpath:keystore/truststore.jks
    trust-store-password: secret
    client-auth: need
