spring:
  data:
    mongodb:
      database: fraud_check
      port: 27017
      host: localhost

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
