spring.application.name: fraud-check

spring.datasource:
  url: jdbc:h2:mem:transdb
  driverClassName: org.h2.Driver
  username: sa
  password:

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: update

spring.h2.console.enabled: true
spring.jpa.open-in-view: false

spring.main.allow-bean-definition-overriding: true

spring.security.user.password: test123

server.error.include-message: always

management.health:
  circuitbreakers.enabled: true
  circuitbreakerevents.enabled: true
  ratelimiters.enabled: true
management.endpoints.web.exposure.include: health,info,metrics,circuitbreakers,circuitbreakerevents,ratelimiters,httptrace

thread.pool.core.size: 10
thread.pool.max.size: 50

rest.template.connection.timeout.millis: 100
rest.template.read.timeout.millis: 100

card.service.url: https://card-service:9090
terminal.service.url: http://localhost:8080/mock

fraud.amount.threshold.value: 1000
fraud.amount.threshold.currency: USD
fraud.card.transactions.range.hours: 24
fraud.terminal.transactions.range.hours: 24

encryption.service.secret: decidelater
encryption.service.algorithm: PBEWithMD5AndTripleDES

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 100
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException
        - java.net.UnknownHostException
        - com.pql.fraudcheck.exception.TerminalException
        - java.io.IOException
        - org.springframework.web.client.ResourceAccessException

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 15
      minimumNumberOfCalls: 50
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10000
      slowCallDurationThreshold: 1000
      slowCallRateThreshold: 75
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException
        - java.net.UnknownHostException
        - com.pql.fraudcheck.exception.TerminalException
